/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotauthRouteImport } from './routes/_notauth'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthProfilesRouteImport } from './routes/_auth/profiles'
import { Route as AuthDocumentsRouteImport } from './routes/_auth/documents'
import { Route as AuthCreditsRouteImport } from './routes/_auth/credits'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as AuthApiKeysRouteImport } from './routes/_auth/api-keys'
import { Route as NotauthAuthRegisterRouteImport } from './routes/_notauth/auth/register'
import { Route as NotauthAuthLoginRouteImport } from './routes/_notauth/auth/login'
import { Route as NotauthAuthForgotPasswordRouteImport } from './routes/_notauth/auth/forgot-password'
import { Route as AuthInviteInviteIdRouteImport } from './routes/_auth/invite/$inviteId'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'

const NotauthRoute = NotauthRouteImport.update({
  id: '/_notauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfilesRoute = AuthProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentsRoute = AuthDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCreditsRoute = AuthCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRoute,
} as any)
const AuthApiKeysRoute = AuthApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthRoute,
} as any)
const NotauthAuthRegisterRoute = NotauthAuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => NotauthRoute,
} as any)
const NotauthAuthLoginRoute = NotauthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => NotauthRoute,
} as any)
const NotauthAuthForgotPasswordRoute =
  NotauthAuthForgotPasswordRouteImport.update({
    id: '/auth/forgot-password',
    path: '/auth/forgot-password',
    getParentRoute: () => NotauthRoute,
  } as any)
const AuthInviteInviteIdRoute = AuthInviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/api-keys': typeof AuthApiKeysRoute
  '/chat': typeof AuthChatRoute
  '/credits': typeof AuthCreditsRoute
  '/documents': typeof AuthDocumentsRoute
  '/profiles': typeof AuthProfilesRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/invite/$inviteId': typeof AuthInviteInviteIdRoute
  '/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/auth/login': typeof NotauthAuthLoginRoute
  '/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRoutesByTo {
  '/api-keys': typeof AuthApiKeysRoute
  '/chat': typeof AuthChatRoute
  '/credits': typeof AuthCreditsRoute
  '/documents': typeof AuthDocumentsRoute
  '/profiles': typeof AuthProfilesRoute
  '/settings': typeof AuthSettingsRoute
  '/': typeof AuthIndexRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/invite/$inviteId': typeof AuthInviteInviteIdRoute
  '/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/auth/login': typeof NotauthAuthLoginRoute
  '/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_notauth': typeof NotauthRouteWithChildren
  '/_auth/api-keys': typeof AuthApiKeysRoute
  '/_auth/chat': typeof AuthChatRoute
  '/_auth/credits': typeof AuthCreditsRoute
  '/_auth/documents': typeof AuthDocumentsRoute
  '/_auth/profiles': typeof AuthProfilesRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/invite/$inviteId': typeof AuthInviteInviteIdRoute
  '/_notauth/auth/forgot-password': typeof NotauthAuthForgotPasswordRoute
  '/_notauth/auth/login': typeof NotauthAuthLoginRoute
  '/_notauth/auth/register': typeof NotauthAuthRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/api-keys'
    | '/chat'
    | '/credits'
    | '/documents'
    | '/profiles'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/invite/$inviteId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api-keys'
    | '/chat'
    | '/credits'
    | '/documents'
    | '/profiles'
    | '/settings'
    | '/'
    | '/admin/users'
    | '/invite/$inviteId'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/_auth'
    | '/_notauth'
    | '/_auth/api-keys'
    | '/_auth/chat'
    | '/_auth/credits'
    | '/_auth/documents'
    | '/_auth/profiles'
    | '/_auth/settings'
    | '/_auth/'
    | '/_auth/admin/users'
    | '/_auth/invite/$inviteId'
    | '/_notauth/auth/forgot-password'
    | '/_notauth/auth/login'
    | '/_notauth/auth/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  NotauthRoute: typeof NotauthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_notauth': {
      id: '/_notauth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NotauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/profiles': {
      id: '/_auth/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof AuthProfilesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documents': {
      id: '/_auth/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthDocumentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/credits': {
      id: '/_auth/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthCreditsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/api-keys': {
      id: '/_auth/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AuthApiKeysRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_notauth/auth/register': {
      id: '/_notauth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof NotauthAuthRegisterRouteImport
      parentRoute: typeof NotauthRoute
    }
    '/_notauth/auth/login': {
      id: '/_notauth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof NotauthAuthLoginRouteImport
      parentRoute: typeof NotauthRoute
    }
    '/_notauth/auth/forgot-password': {
      id: '/_notauth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof NotauthAuthForgotPasswordRouteImport
      parentRoute: typeof NotauthRoute
    }
    '/_auth/invite/$inviteId': {
      id: '/_auth/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof AuthInviteInviteIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthApiKeysRoute: typeof AuthApiKeysRoute
  AuthChatRoute: typeof AuthChatRoute
  AuthCreditsRoute: typeof AuthCreditsRoute
  AuthDocumentsRoute: typeof AuthDocumentsRoute
  AuthProfilesRoute: typeof AuthProfilesRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthInviteInviteIdRoute: typeof AuthInviteInviteIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthApiKeysRoute: AuthApiKeysRoute,
  AuthChatRoute: AuthChatRoute,
  AuthCreditsRoute: AuthCreditsRoute,
  AuthDocumentsRoute: AuthDocumentsRoute,
  AuthProfilesRoute: AuthProfilesRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthInviteInviteIdRoute: AuthInviteInviteIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface NotauthRouteChildren {
  NotauthAuthForgotPasswordRoute: typeof NotauthAuthForgotPasswordRoute
  NotauthAuthLoginRoute: typeof NotauthAuthLoginRoute
  NotauthAuthRegisterRoute: typeof NotauthAuthRegisterRoute
}

const NotauthRouteChildren: NotauthRouteChildren = {
  NotauthAuthForgotPasswordRoute: NotauthAuthForgotPasswordRoute,
  NotauthAuthLoginRoute: NotauthAuthLoginRoute,
  NotauthAuthRegisterRoute: NotauthAuthRegisterRoute,
}

const NotauthRouteWithChildren =
  NotauthRoute._addFileChildren(NotauthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  NotauthRoute: NotauthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
